{
 "title": "Scripts usando Outis",
 "description": "Interface gráfica para monitoramento e análise de dados de rotina",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Routine Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_routine_latency_sum", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Summary",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "avg by(name) (app_summary)", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "Routines Outis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "count by(name) (app_routine)", "legendFormat": "{{ name }}" }
   ]
  }
 ]
}